/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Name = string;
export type SchoolYear = number;
export type Requisite = "require" | "require_elective" | "elective";
export type SubjectCategory = "general" | "pe" | "fl" | "chembio" | "photon" | "infosys" | "teacher" | "unknown";
export type IsCapTarget = boolean;
export type LectureType = string;
export type Credits = number;
export type TeacherNames = string[];
export type CreditManager = string;
export type Summary = string;
export type Goal = string;
export type Title = string;
export type Point = number;
export type Way = string;
export type EvaluationItems = EvaluationItem[];
export type Cources = string[];
export type SelfStudy = string;
export type Textbook = string;
export type Reference = string;
export type Title1 = string;
export type Point1 = number;
export type EvaluationEvents = EvaluationEvent[];
export type EvaluationCriterion = string;
export type AdditionalInformation = string;
export type Subjects = Subject[];

export interface Syllabus {
  subjects: Subjects;
  [k: string]: unknown;
}
export interface Subject {
  name: Name;
  school_year: SchoolYear;
  requisite: Requisite;
  category: SubjectCategory;
  is_CAP_target: IsCapTarget;
  lecture_type: LectureType;
  credits: Credits;
  teacher_names: TeacherNames;
  credit_manager: CreditManager;
  summary: Summary;
  goal: Goal;
  evaluation_items: EvaluationItems;
  cources: Cources;
  self_study: SelfStudy;
  textbook: Textbook;
  reference: Reference;
  evaluation_events: EvaluationEvents;
  evaluation_criterion: EvaluationCriterion;
  additional_information: AdditionalInformation;
  [k: string]: unknown;
}
export interface EvaluationItem {
  title: Title;
  point: Point;
  way: Way;
  [k: string]: unknown;
}
export interface EvaluationEvent {
  title: Title1;
  point: Point1;
  [k: string]: unknown;
}
